<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="username" class="form-label">
                Choose a username
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                Enter your email
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                Choose a password
            </label>
            <input type="password" name="password" id="password" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
                Confirm your password
            </label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control"/>
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary">Register</button>
        </fieldset>
    </form>
    <p>
        You already have an account ? <a href="index.php"> Login here </a>
    </p>
</main>